### ISSUE TITLE
practica5sprint2 button

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-ang3-l32#2]
[practica 5sprint2 button.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-ang3-l32/files/8354321/practica.5sprint2.button.pdf)

**Comment by Yareli-Perez** [comment]
calificación 72 = 14.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
